#!/bin/bash -l
#SBATCH --job-name="nccl-build"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1        # Do not change
#SBATCH --partition=normal
#SBATCH --account=a-g34
#SBATCH --time=02:20:00            # total run time limit (HH:MM:SS)
#SBATCH --output=nccl_build.%j.o
#SBATCH --error=nccl_build.%j.e

srun --environment=megatron bash -c "
cd /users/zhu/nccl_npkit_v2.20.5-1/nccl
make clean

export NPKIT_FLAG=\"-DENABLE_NPKIT\"
export NPKIT_ALLREDUCE_FLAGS=\"-DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_EXIT \
 -DENABLE_NPKIT_EVENT_GPU_SEND_ENTRY -DENABLE_NPKIT_EVENT_GPU_SEND_EXIT \
 -DENABLE_NPKIT_EVENT_GPU_RECV_REDUCE_SEND_ENTRY -DENABLE_NPKIT_EVENT_GPU_RECV_REDUCE_SEND_EXIT \
 -DENABLE_NPKIT_EVENT_GPU_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_GPU_DIRECT_RECV_REDUCE_COPY_SEND_EXIT \
 -DENABLE_NPKIT_EVENT_GPU_DIRECT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_GPU_DIRECT_RECV_COPY_SEND_EXIT \
 -DENABLE_NPKIT_EVENT_GPU_DIRECT_RECV_ENTRY -DENABLE_NPKIT_EVENT_GPU_DIRECT_RECV_EXIT\"
export NPKIT_PRIMS_SIMPLE_FLAGS=\"-DENABLE_NPKIT_EVENT_PRIM_SIMPLE_DATA_PROCESS_ENTRY -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_DATA_PROCESS_EXIT\"
export NPKIT_PRIMS_LL_FLAGS=\"-DENABLE_NPKIT_EVENT_PRIM_LL_DATA_PROCESS_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL_DATA_PROCESS_EXIT\"
export NPKIT_FLAGS=\"\$NPKIT_FLAG \$NPKIT_ALLREDUCE_FLAGS \$NPKIT_PRIMS_SIMPLE_FLAGS \$NPKIT_PRIMS_LL_FLAGS\"
export TRACING_FLAGS=\"\$NPKIT_FLAGS\"

make -j src.build CUDA_HOME=/usr/local/cuda NVCC_GENCODE=\"-gencode=arch=compute_90,code=sm_90\" TRACING_FLAGS=\"\$TRACING_FLAGS\"
"
